# Default base image 
ARG BASE_IMAGE=ubuntu
# Default release is 24.04
ARG BASE_IMAGE_RELEASE=24.04

# install all nodejs modules
# build nodejs module
# create /composer/node
# use FROM BASE_IMAGE
# define FROM before use ENV command
FROM ${BASE_IMAGE}:${BASE_IMAGE_RELEASE}

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	fontconfig \
	git \
	ca-certificates 

RUN apt-get install -y --no-install-recommends \
	gtk-update-icon-cache

COPY usr/share/themes/ /usr/share/themes/ 

RUN git clone https://github.com/abcdesktopio/Win11OS-kde.git && \
    cd Win11OS-kde && \
    ./install.sh 

RUN git clone https://github.com/abcdesktopio/Win11-icon-theme.git && \
    cd Win11-icon-theme && \
    ./install.sh

# 
# COPY files files  
# # copy themes from abcdesktopio/oc.themes:4.0
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/themes /usr/share/themes
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/icons /usr/share/icons
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/aurorae/themes /usr/share/aurorae/themes
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/color-schemes /usr/share/color-schemes
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/plasma/desktoptheme /usr/share/plasma/desktoptheme
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/plasma/layout-templates /usr/share/plasma/layout-templates
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/plasma/look-and-feel /usr/share/plasma/look-and-feel
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/Kvantum /usr/share/Kvantum
# COPY --from=abcdesktopio/oc.themes:4.0 /usr/share/wallpapers /usr/share/wallpapers


