ARG TARGETPLATFORM
ARG BUILDPLATFORM
# Default release is 22.04
ARG TAG=latest
# Default base image 
ARG BASE_IMAGE
ARG BASE_IMAGE_RELEASE
ARG DRIVER_VERSION
#
# The main oc.user start here
#
FROM ${BASE_IMAGE}:${BASE_IMAGE_RELEASE}

USER 0

ARG DRIVER_VERSION

# convert ARG to ENV with same name
ENV TARGET_MODE=$TARGET_MODE
ENV DRIVER_VERSION=$DRIVER_VERSION

# Make all NVIDIA GPUs visible by default
ENV NVIDIA_VISIBLE_DEVICES all
# All NVIDIA driver capabilities should preferably be used, check `NVIDIA_DRIVER_CAPABILITIES` inside the container if things do not work
ENV NVIDIA_DRIVER_CAPABILITIES all
# Disable VSYNC for NVIDIA GPUs



# install for nvidia
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        mesa-utils \
        drm-info \
        libglvnd0 \
	wget \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#
# Install Xorg and other important libraries or packages
RUN apt-get update && apt-get install --no-install-recommends -y \
        # Install essential Xorg and NVIDIA packages, packages above this line should be the same between docker-nvidia-glx-desktop and docker-nvidia-egl-desktop
        libc6-dev \
        libpci3 \
        xcvt \
        vim \
	pkg-config \
        libelf-dev \
        libglvnd-dev \
        libglvnd0 && \
    rm -rf /var/lib/apt/lists/*

RUN echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf && \
    ldconfig

# Install operating system libraries or packages
RUN apt-get update && apt-get install --no-install-recommends -y \
      vulkan-tools \
      mesa-utils \
      kmod \
      drm-info && \
    rm -rf /var/lib/apt/lists/*

ENV TERM=linux
# install nvidia modules
RUN cd /tmp && \ 
  echo DRIVER_VERSION=\"$DRIVER_VERSION\" && \
  curl -fsL -O "https://us.download.nvidia.com/XFree86/Linux-x86_64/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" || curl -fsL -O "https://us.download.nvidia.com/tesla/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" || { echo "Failed NVIDIA GPU driver download. Exiting."; exit 1; } && \
  chmod 755 "NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" && \
  ./NVIDIA-Linux-x86_64-$DRIVER_VERSION.run -x && \
  ls -la && \
  cd "NVIDIA-Linux-x86_64-$DRIVER_VERSION" && \
  ./nvidia-installer --silent \
		    --no-systemd \
                    --no-kernel-module \
                    --no-nouveau-check \
                    --no-nvidia-modprobe \
                    --no-rpms \
                    --no-backup \
                    --no-check-for-alternate-installs && \
  rm -rf /tmp/NVIDIA*

# Configure EGL manually
RUN mkdir -p /usr/share/glvnd/egl_vendor.d/ && \
    echo "{\n\
             \"file_format_version\" : \"1.0.0\",\n\
             \"ICD\": {\n\"library_path\": \"libEGL_nvidia.so.0\"\n }\n \
    }" > /usr/share/glvnd/egl_vendor.d/10_nvidia.json

ENV __GL_SYNC_TO_VBLANK 0

# NAME="Ubuntu"
# VERSION_ID="22.04"
#RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
#    apt-get update && apt-get install --no-install-recommends -y ./cuda-keyring_1.1-1_all.deb && \
#    rm -rf /var/lib/apt/lists/*


# set build date
RUN date > /etc/build.date

# Set for compatibility 2.0
WORKDIR /home/$BUSER
USER $BUSER
