ARG TARGETPLATFORM
ARG BUILDPLATFORM
# Default release is 22.04
ARG TAG=latest
# Default base image 
ARG BASE_IMAGE
ARG BASE_IMAGE_RELEASE

# ABCDESKTOP_LOCALACCOUNT_DIR arg
# use in ENV ABCDESKTOP_LOCALACCOUNT_DIR=$ABCDESKTOP_LOCALACCOUNT_DIR
# release >= 3.1 set value to "/etc/localaccount"
# release <  3.1 set value to "/var/secrets/abcdesktop/localaccount"
ARG ABCDESKTOP_LOCALACCOUNT_DIR
# ="/etc/localaccount"

#
# create package for openbox
# deb files will be located in /root/packages/$(uname -m) directory 
# patched with openbox.title.patch for abcdesktop
FROM ${BASE_IMAGE}:${BASE_IMAGE_RELEASE}
ARG TARGET_MODE
USER 0
# install sudo 
# install qterminal xfonts-base
# allow all users to run sudo commands
# remove it if need
RUN /composer/unaccount.sh
RUN if [ "${TARGET_MODE}" != "hardening" ]; then apt-get update && apt-get install -y --no-install-recommends sudo nmapsi4 && apt-get clean && rm -rf /var/lib/apt/lists/* && echo "ALL ALL=(ALL:ALL) ALL" > /etc/sudoers.d/all; fi

# change passwd shadow group gshadow
RUN mkdir -p $ABCDESKTOP_LOCALACCOUNT_DIR && \
    for f in passwd shadow group gshadow ; do if [ -f /etc/$f ] ; then cp /etc/$f $ABCDESKTOP_LOCALACCOUNT_DIR ; rm -f /etc/$f; ln -s $ABCDESKTOP_LOCALACCOUNT_DIR/$f /etc/$f; fi; done

USER $BUSER
