ARG BASE_IMAGE=dummy
ARG BASE_IMAGE_RELEASE=release
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TAG=latest
#
# create package for openbox
# deb files will be located in /root/packages/$(uname -m) directory 
# patched with openbox.title.patch for abcdesktop
FROM ${BASE_IMAGE}:${BASE_IMAGE_RELEASE}
ARG TARGET_MODE
ENV TARGET_MODE=$TARGET_MODE
# install sudo 
# install qterminal xfonts-base
# allow all users to run sudo commands
# remove it if need
# RUN /composer/unaccount.sh
RUN if [ "${TARGET_MODE}" != "hardening" ]; then apt-get update && apt-get reinstall -y --no-install-recommends sudo vim ssh && apt-get clean && rm -rf /var/lib/apt/lists/*; fi

