[program:kwin]
priority=50
command=bash -c "until [ -S /tmp/.X11-unix/X0 ]; do sleep 1; done; exec /usr/bin/kwin_x11"
stdout_logfile=/var/log/desktop/kwin.log
autostart=true
autorestart=true
redirect_stderr=true
