[program:plasmashell]
command=bash -c "until [ -S /tmp/.X11-unix/X0 ]; do sleep 1; done; /usr/bin/plasmashell"
stdout_logfile=/var/log/desktop/plasmashell.log
autostart=false
autorestart=true
redirect_stderr=true
