[program:plasmashell]
; /usr/bin/startplasma-x11
command=bash -c "until [ -S /tmp/.X11-unix/X0 ]; do sleep 1; done; exec /usr/bin/plasmashell"
#command=bash -c "until [ -S /tmp/.X11-unix/X0 ]; do sleep 0.2; done; /usr/bin/startplasma-x11"
stdout_logfile=/var/log/desktop/plasmashell.log
autostart=true
autorestart=true
redirect_stderr=true
