[program:xfwm4]
priority=50
; --sm-disable
;   Do not connect to the session manager.
command=bash -c "until [ -S /tmp/.X11-unix/X0 ]; do sleep 1; done; /usr/bin/xfwm4 --sm-client-disable"
stdout_logfile=/var/log/desktop/xfwm4.log
autostart=true
autorestart=true
redirect_stderr=true
