[qt]
GUIEffects=none
KDE\contrast=7
KWinPalette\activeBackground=#36393e
KWinPalette\activeBlend=#3b3e44
KWinPalette\activeForeground=#dcdcdc
KWinPalette\activeTitleBtnBg=#fafafa
KWinPalette\frame=#fafafa
KWinPalette\inactiveBackground=#3e4147
KWinPalette\inactiveBlend=#43474d
KWinPalette\inactiveForeground=#787878
KWinPalette\inactiveFrame=#f7f7f7
KWinPalette\inactiveTitleBtnBg=#f7f7f7
Palette\active=#333333, #fafafa, #d0d0d0, #e6e6e6, #b6b6b6, #d0d0d0, #323232, #ffffff, #333333, #f0f0f0, #fafafa, #828282, #e6e6e6, #323232, #4285f4, #e040fb, #e6e6e6, #000000, #505050, #dcdcdc, #969696, #e6e6e6
Palette\disabled=#b4b4b4, #fafafa, #d0d0d0, #e6e6e6, #b6b6b6, #d0d0d0, #aeaeae, #ffffff, #b4b4b4, #f0f0f0, #fafafa, #828282, #fafafa, #b4b4b4, #b3cbf1, #eab2f4, #e6e6e6, #000000, #505050, #dcdcdc, #d1d1d1, #fafafa
Palette\inactive=#353535, #f7f7f7, #ffffff, #ffffff, #787878, #c5c5c5, #343434, #ffffff, #353535, #ededed, #f7f7f7, #3d3c3c, #e8e8e8, #353535, #3c88e6, #de44f4, #e3e3e3, #000000, #505050, #dcdcdc, #959595, #e8e8e8
font="Selawik,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
