name: Test oc.user images

on:
  pull_request:
    branches: [ main ]
jobs:
  build_and_test_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps: 
    - name: Clone repository
      run: |
        rm -rf ..?* .[!.]* *
        git clone "https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@github.com/abcdesktopio/oc.user.18.04.git" .
        git submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image oc.user.${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker build . -t abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev --build-arg BASE_IMAGE_RELEASE:${{ matrix.BASE_IMAGE_RELEASE }} --build-arg BASE_IMAGE=abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }} --build-arg TAG:dev

    - name: Run and test docker image oc.user.${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        ./make-test.sh ${{ matrix.BASE_IMAGE_RELEASE }}
