name: Build and test oc.user images linux arm v7

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [
      dispatch-from-pulse,
      dispatch-from-cups,
      dispatch-from-oc.software,
      dispatch-from-file-service,
      dispatch-from-printer-service
    ]
jobs:
  update_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 21.04]
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Run Buildx oc.user.${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
          docker buildx build \
            --build-arg BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }} \
            --build-arg BASE_IMAGE=abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }} \
            --build-arg TAG:dev \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --tag abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev \
            --file ./Dockerfile .
            
    - name: Run Buildx oc.user.${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
          docker buildx build \
            --build-arg BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }} \
            --build-arg BASE_IMAGE=abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }} \
            --build-arg TAG:dev \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --tag abcdesktopio/oc.user.kubernetes.${{ matrix.BASE_IMAGE_RELEASE }}:dev \
            --file ./Dockerfile.kubernetes .
            
    - name: Run and test docker image ${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        ./make-test.sh ${{ matrix.BASE_IMAGE_RELEASE }}:dev

    - name: Push image abcdesktopio/${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker push abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev
        docker push abcdesktopio/oc.user.kubernetes.${{ matrix.BASE_IMAGE_RELEASE }}:dev

  dispatch_oc_user_debuger:
    runs-on: ubuntu-latest
    needs: update_image
    steps:
      - name: Dispatch repository oc.user.debuger
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user.debuger
          event-type: dispatch-from-oc.user

      - name: Dispatch repository oc.user.nvidia
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user.nvidia
          event-type: dispatch-from-oc.user

      - name: Dispatch repository oc.user.tunnel
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user.tunnel
          event-type: dispatch-from-oc.user
