name: Build and test oc.user images linux amd64

on:
  push:
    branches: [ main ]
    
env:
  TEST_TAG: abcdesktopio/oc.user:test
  
jobs:
  update_image:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Run Buildx oc.user.alpine
      run: |
          echo "kubernetes" > TARGET_MODE
          ./mkversion.sh
     
    - name: Build test image ${{ env.TEST_TAG }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        platforms: linux/amd64
        load: true
        build-args: |
          TAG=22.04
          BASE_IMAGE_RELEASE=22.04
          BASE_IMAGE=ubuntu
        tags: ${{ env.TEST_TAG }}

    - name: Run and test docker image ${{ env.TEST_TAG }}
      run: |
        ./make-test.sh ${{ env.TEST_TAG }}
    
    - name: Build and push image oc.user.ubuntu:3.0
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        platforms: linux/amd64, linux/arm64
        push: true
        build-args: |
          TAG=22.04
          BASE_IMAGE_RELEASE=22.04
          BASE_IMAGE=ubuntu
        tags: abcdesktopio/oc.user.ubuntu:3.0
        
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: abcdesktopio/oc.user.ubuntu:3.0
        format: 'sarif'
        output: oc.user.ubuntu.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: oc.user.ubuntu.sarif
  

