name: Build and test oc.user images linux/amd64, linux/arm64

on:
  push:
  
env: 
  imagetag: ${{ github.head_ref || github.ref_name || 'dev' }}
    
jobs:
  update_image:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: "image tag"
      run: echo "image tag set to '${{ env.imagetag }}'"

    - name: Run Buildx oc.user
      run: |
          echo "kubernetes" > TARGET_MODE
          ./mkversion.sh
     
    - name: Build test image abcdesktopio/oc.user:test
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        platforms: linux/amd64, linux/arm64
        push: true
        build-args: |
          TAG=22.04
          BASE_IMAGE_RELEASE=22.04
          BASE_IMAGE=ubuntu
        tags: abcdesktopio/oc.user:test.${{ env.imagetag }}

    - name: Run and test docker image abcdesktopio/oc.user:test
      run: |
        ./make-test.sh abcdesktopio/oc.user:test.${{ env.imagetag }}
    
    - name: Build and push image oc.user.ubuntu:${{ env.imagetag }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.ubuntu
        platforms: linux/amd64, linux/arm64
        push: true
        build-args: |
          TAG=22.04
          BASE_IMAGE_RELEASE=22.04
          BASE_IMAGE=ubuntu
        tags: abcdesktopio/oc.user.ubuntu:${{ env.imagetag }}
  

