name: Test and update oc.user images

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [
      dispatch-from-pulse,
      dispatch-from-cups,
      dispatch-from-oc.software,
      dispatch-from-file-service,
      dispatch-from-printer-service
    ]
jobs:
  test_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build image abcdesktopio/${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker build . -t abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev --build-arg BASE_IMAGE_RELEASE:${{ matrix.BASE_IMAGE_RELEASE }} --build-arg BASE_IMAGE=abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }} --build-arg TAG:dev

    - name: Run and test docker image ${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        ./make-test.sh ${{ matrix.BASE_IMAGE_RELEASE }}

  update_images:
    runs-on: ubuntu-latest
    needs: test_images
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev
          build-args: |
            BASE_IMAGE_RELEASE:${{ matrix.BASE_IMAGE_RELEASE }}
            BASE_IMAGE=abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }}
            TAG=dev

  dispatch_oc_user_debuger:
    runs-on: ubuntu-latest
    needs: update_images
    steps:
      - name: Dispatch repository oc.user
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user.tunnel
          event-type: dispatch-from-oc.user

      - name: Dispatch repository oc.user.debuger
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user.debuger
          event-type: dispatch-from-oc.user
