name: Test and update oc.user images

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [dispatch-from-pulse, dispatch-from-cups, dispatch-from-oc.software.18.04]
jobs:
  update_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps: 
    - name: Clone repository
      run: |
        rm -rf ..?* .[!.]* *
        git clone "https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@github.com/abcdesktopio/oc.user.18.04.git" .
        git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" submodule update --init --recursive --remote

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build image abcdesktopio/${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker build . -t abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev --build-arg BASE_IMAGE_RELEASE:${{ matrix.BASE_IMAGE_RELEASE }} --build-arg BASE_IMAGE=abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }} --build-arg TAG:dev

    - name: Run and test docker image ${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        ./make-test.sh ${{ matrix.BASE_IMAGE_RELEASE }}

    - name: Push image abcdesktopio/${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker push abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }}:dev
  dispatch_oc_user_debuger:
    - name: Dispatch repository oc.user.debuger
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TOKEN_DISPATCH }}
        repository: abcdesktopio/oc.user.debuger
        event-type: dispatch-from-oc.user
